# Install script for directory: /home/extra/src/Squeak-4.0.3.2202-src/unix

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "/usr/local")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

# Install shared libraries without execute permission?
IF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  SET(CMAKE_INSTALL_SO_NO_EXE "1")
ENDIF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/squeak/4.0.3-2202" TYPE PROGRAM FILES "/home/extra/src/Squeak-4.0.3.2202-src/build/squeakvm")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE PROGRAM FILES "/home/extra/src/Squeak-4.0.3.2202-src/build/squeak")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE PROGRAM FILES "/home/extra/src/Squeak-4.0.3.2202-src/build/squeak.sh")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/man/man1" TYPE FILE FILES "/home/extra/src/Squeak-4.0.3.2202-src/build/squeak.1")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/ADPCMCodecPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/AsynchFilePlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/BMPReadWriterPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/B2DPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/BitBltPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/CroquetPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/DSAPrims/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/ZipPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/DropPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/FFTPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/FilePlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/FloatArrayPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/FloatMathPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/GeniePlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/JPEGReadWriter2Plugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/JPEGReaderPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/JoystickTabletPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/Klatt/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/LargeIntegers/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/LocalePlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/Matrix2x3Plugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/MiscPrimitivePlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/RePlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/SecurityPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/SerialPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/SocketPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/SoundCodecPrims/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/SoundGenerationPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/SoundPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/StarSqueakPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/SurfacePlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/UUIDPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/B3DAcceleratorPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/Squeak3D/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/ClipboardExtendedPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/DBusPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/SqueakFFIPrims/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/FT2Plugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/FileCopyPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/GStreamerPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/HostWindowPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/ImmX11Plugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/KedamaPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/KedamaPlugin2/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/MIDIPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/Mpeg3Plugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/OggPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/PseudoTTYPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/RomePlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/AioPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/UnixOSProcessPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/XDisplayControlPlugin/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/vm-sound-OSS/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/vm-display-fbdev/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/vm-sound-null/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/vm-sound-NAS/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/vm-display-X11/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/vm-sound-ALSA/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/vm-display-custom/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/vm-display-null/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/vm-sound-custom/cmake_install.cmake")
  INCLUDE("/home/extra/src/Squeak-4.0.3.2202-src/build/vm-sound-pulse/cmake_install.cmake")

ENDIF(NOT CMAKE_INSTALL_LOCAL_ONLY)

IF(CMAKE_INSTALL_COMPONENT)
  SET(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
ELSE(CMAKE_INSTALL_COMPONENT)
  SET(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
ENDIF(CMAKE_INSTALL_COMPONENT)

FILE(WRITE "/home/extra/src/Squeak-4.0.3.2202-src/build/${CMAKE_INSTALL_MANIFEST}" "")
FOREACH(file ${CMAKE_INSTALL_MANIFEST_FILES})
  FILE(APPEND "/home/extra/src/Squeak-4.0.3.2202-src/build/${CMAKE_INSTALL_MANIFEST}" "${file}\n")
ENDFOREACH(file)
